# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17zMovGt3aVKYEfjuw88D9uhFuAkjTLxP
"""

import pandas as pd
import streamlit as st
import seaborn as sns
import matplotlib.pyplot as plt

st.set_page_config(page_title="U.S. College ROI Dashboard", layout="wide")

st.title("U.S. College ROI Dashboard")

# Load data
@st.cache_data
def load_data():
    df = pd.read_csv("college_scorecard_small.csv", low_memory=False)
    for col in ['Cost', 'MedianDebt', 'MedianEarnings', 'UndergradSize']:
        df[col] = pd.to_numeric(df[col], errors='coerce')
    df.dropna(inplace=True)
    return df

df = load_data()

# Sidebar filters
st.sidebar.header("Filters")
state = st.sidebar.selectbox("Select a State", sorted(df['State'].unique()))
cost_min, cost_max = st.sidebar.slider("Cost Range ($)", 0, 80000, (10000, 50000), 1000)

filtered = df[(df['State'] == state) & (df['Cost'].between(cost_min, cost_max))]

# Scatter Plot
st.subheader(f"Cost vs Median Earnings in {state}")
fig1, ax1 = plt.subplots()
sns.scatterplot(data=filtered, x='Cost', y='MedianEarnings', ax=ax1)
plt.xlabel("Tuition Cost ($)")
plt.ylabel("Median Earnings ($)")
st.pyplot(fig1)

# Correlation Heatmap
st.subheader("Correlation: Cost, Debt, Earnings")
fig2, ax2 = plt.subplots()
sns.heatmap(df[['Cost', 'MedianDebt', 'MedianEarnings']].corr(), annot=True, cmap='coolwarm', ax=ax2)
st.pyplot(fig2)

# Bar Chart: Top 10 States by Avg Earnings
st.subheader("Top 10 States by Median Earnings")
state_avg = (
    df.groupby('State')['MedianEarnings']
    .mean()
    .sort_values(ascending=False)
    .head(10)
)
fig3, ax3 = plt.subplots()
state_avg.plot(kind='barh', ax=ax3, color='green')
ax3.set_xlabel("Median Earnings ($)")
ax3.set_ylabel("State")
ax3.invert_yaxis()
st.pyplot(fig3)

# Graduation Rate Histogram (optional if you added it in dataset)
# st.subheader("Distribution of Graduation Rates")

st.markdown("Made by Haniya Khan | Dataset: U.S. College Scorecard")
